apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-name-api #MUST BE CHANGED
  namespace: NAMESPACE_SQUAD_NAME #MUST BE CHANGED
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-name-api-pod #MUST BE CHANGED
  template:
    metadata:
      labels:
        app: service-name-api-pod #MUST BE CHANGED
    spec:
      containers:
        - name: service-name-api-app #MUST BE CHANGED
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.sa-east-1.amazonaws.com/bella-fm/REPOSITORY_NAME:${TAG_IMAGE} #MUST BE CHANGED REPOSITORY_NAME_CHANGE VALUE
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SAMPLE_VAR #MUST BE CHANGED, COMING FROM GITHUB ACTION PIPELINE
              value: ${SAMPLE_VAR} #MUST BE CHANGED
            - name: JAEGER_AGENT_HOST
              value: tempo.bella-observability
            - name: JAEGER_AGENT_PORT
              value: '6831'
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: service-name-api-service #MUST BE CHANGED
  namespace: NAMESPACE_SQUAD_NAME #MUST BE CHANGED
spec:
  selector:
    app: service-name-api-pod #MUST BE CHANGED
  type: ClusterIP
  ports:
   - port: 80
     targetPort: 8080

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: service-name-api-ingress #MUST BE CHANGED
  namespace: NAMESPACE_SQUAD_NAME #MUST BE CHANGED
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "false"
    #nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,token"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE, PATCH"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.dev.zuppfm.com"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/body-size: "0"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.org/client-max-body-size: "0"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

spec:
  rules:
    - host: service-name-api${ENV}zuppfm.com #MUST BE CHANGED
      http:
        paths:
          - backend:
              serviceName: service-name-api-service #MUST BE CHANGED
              servicePort: 80
